// <auto-generated />
using System;
using FPNg.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FPNg.API.Data.Migrations
{
    [DbContext(typeof(FPNgContext))]
    [Migration("20210821132844_Update-Procedure-2-SpCreateLedgerReadout")]
    partial class UpdateProcedure2SpCreateLedgerReadout
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FPNg.API.Data.Domain.Credit", b =>
                {
                    b.Property<int>("PkCredit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<int?>("AnnualDom")
                        .HasColumnType("int")
                        .HasColumnName("AnnualDOM");

                    b.Property<int?>("AnnualMoy")
                        .HasColumnType("int")
                        .HasColumnName("AnnualMOY");

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("date");

                    b.Property<int?>("BiMonthlyDay1")
                        .HasColumnType("int");

                    b.Property<int?>("BiMonthlyDay2")
                        .HasColumnType("int");

                    b.Property<bool>("DateRangeReq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("EverOtherWeekDow")
                        .HasColumnType("int")
                        .HasColumnName("EverOtherWeekDOW");

                    b.Property<int?>("FkPeriod")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyDom")
                        .HasColumnType("int")
                        .HasColumnName("MonthlyDOM");

                    b.Property<string>("Name")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("Quarterly1Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly1Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly2Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly2Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly3Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly3Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly4Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly4Month")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual1Day")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual1Month")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual2Day")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual2Month")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WeeklyDow")
                        .HasColumnType("int")
                        .HasColumnName("WeeklyDOW");

                    b.HasKey("PkCredit");

                    b.HasIndex("FkPeriod");

                    b.ToTable("Credits", "ItemDetail");
                });

            modelBuilder.Entity("FPNg.API.Data.Domain.Debit", b =>
                {
                    b.Property<int>("PkDebit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<int?>("AnnualDom")
                        .HasColumnType("int")
                        .HasColumnName("AnnualDOM");

                    b.Property<int?>("AnnualMoy")
                        .HasColumnType("int")
                        .HasColumnName("AnnualMOY");

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("date");

                    b.Property<int?>("BiMonthlyDay1")
                        .HasColumnType("int");

                    b.Property<int?>("BiMonthlyDay2")
                        .HasColumnType("int");

                    b.Property<bool>("DateRangeReq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("EverOtherWeekDow")
                        .HasColumnType("int")
                        .HasColumnName("EverOtherWeekDOW");

                    b.Property<int?>("FkPeriod")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyDom")
                        .HasColumnType("int")
                        .HasColumnName("MonthlyDOM");

                    b.Property<string>("Name")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("Quarterly1Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly1Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly2Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly2Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly3Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly3Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly4Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly4Month")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual1Day")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual1Month")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual2Day")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual2Month")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WeeklyDow")
                        .HasColumnType("int")
                        .HasColumnName("WeeklyDOW");

                    b.HasKey("PkDebit");

                    b.HasIndex("FkPeriod");

                    b.ToTable("Debits", "ItemDetail");
                });

            modelBuilder.Entity("FPNg.API.Data.Domain.InitialAmount", b =>
                {
                    b.Property<int>("PkInitialAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PkInitialAmount")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PkInitialAmount");

                    b.ToTable("InitialAmount", "ItemDetail");
                });

            modelBuilder.Entity("FPNg.API.Data.Domain.Ledger", b =>
                {
                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<double>("CreditSummary")
                        .HasColumnType("float");

                    b.Property<double>("DebitSummary")
                        .HasColumnType("float");

                    b.Property<int?>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Net")
                        .HasColumnType("float");

                    b.Property<DateTime?>("OccurrenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollupKey")
                        .HasColumnType("int");

                    b.Property<double>("RunningTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("WDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.ToTable("Ledgers", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("FPNg.API.Data.Domain.Period", b =>
                {
                    b.Property<int>("PkPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("PkPeriod");

                    b.ToTable("Periods", "ItemDetail");
                });

            modelBuilder.Entity("FPNg.API.Data.Domain.VwCredit", b =>
                {
                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<int?>("AnnualDom")
                        .HasColumnType("int")
                        .HasColumnName("AnnualDOM");

                    b.Property<int?>("AnnualMoy")
                        .HasColumnType("int")
                        .HasColumnName("AnnualMOY");

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("date");

                    b.Property<int?>("BiMonthlyDay1")
                        .HasColumnType("int");

                    b.Property<int?>("BiMonthlyDay2")
                        .HasColumnType("int");

                    b.Property<bool>("DateRangeReq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("EverOtherWeekDow")
                        .HasColumnType("int")
                        .HasColumnName("EverOtherWeekDOW");

                    b.Property<int?>("FkPeriod")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyDom")
                        .HasColumnType("int")
                        .HasColumnName("MonthlyDOM");

                    b.Property<string>("Name")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("PkCredit")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly1Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly1Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly2Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly2Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly3Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly3Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly4Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly4Month")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual1Day")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual1Month")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual2Day")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual2Month")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WeeklyDow")
                        .HasColumnType("int")
                        .HasColumnName("WeeklyDOW");

                    b.ToView("vwCredits", "ItemDetail");
                });

            modelBuilder.Entity("FPNg.API.Data.Domain.VwDebit", b =>
                {
                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<int?>("AnnualDom")
                        .HasColumnType("int")
                        .HasColumnName("AnnualDOM");

                    b.Property<int?>("AnnualMoy")
                        .HasColumnType("int")
                        .HasColumnName("AnnualMOY");

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("date");

                    b.Property<int?>("BiMonthlyDay1")
                        .HasColumnType("int");

                    b.Property<int?>("BiMonthlyDay2")
                        .HasColumnType("int");

                    b.Property<bool>("DateRangeReq")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("EverOtherWeekDow")
                        .HasColumnType("int")
                        .HasColumnName("EverOtherWeekDOW");

                    b.Property<int?>("FkPeriod")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyDom")
                        .HasColumnType("int")
                        .HasColumnName("MonthlyDOM");

                    b.Property<string>("Name")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("PkDebit")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly1Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly1Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly2Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly2Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly3Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly3Month")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly4Day")
                        .HasColumnType("int");

                    b.Property<int?>("Quarterly4Month")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual1Day")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual1Month")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual2Day")
                        .HasColumnType("int");

                    b.Property<int?>("SemiAnnual2Month")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WeeklyDow")
                        .HasColumnType("int")
                        .HasColumnName("WeeklyDOW");

                    b.ToView("vwDebits", "ItemDetail");
                });

            modelBuilder.Entity("FPNg.API.Data.Domain.Credit", b =>
                {
                    b.HasOne("FPNg.API.Data.Domain.Period", "Period")
                        .WithMany("Credits")
                        .HasForeignKey("FkPeriod")
                        .HasConstraintName("FK_Credits_Periods");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("FPNg.API.Data.Domain.Debit", b =>
                {
                    b.HasOne("FPNg.API.Data.Domain.Period", "Period")
                        .WithMany("Debits")
                        .HasForeignKey("FkPeriod")
                        .HasConstraintName("FK_Debits_Periods");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("FPNg.API.Data.Domain.Period", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("Debits");
                });
#pragma warning restore 612, 618
        }
    }
}
